FROM centos:7

# use Centos vault for downloading
RUN sed -i 's/mirror.centos.org/vault.centos.org/g' /etc/yum.repos.d/*.repo && \
    sed -i 's/^#.*baseurl=http/baseurl=http/g' /etc/yum.repos.d/*.repo && \
    sed -i 's/^mirrorlist=http/#mirrorlist=http/g' /etc/yum.repos.d/*.repo

RUN yum install -y centos-release-scl

# installing centos-release-scl adds the Software Collections repo to Yum's configuration,
# so the following replacement should be used for downloading from Centos vault
RUN sed -i 's/mirror.centos.org/vault.centos.org/g' /etc/yum.repos.d/*.repo && \
    sed -i 's/^#.*baseurl=http/baseurl=http/g' /etc/yum.repos.d/*.repo && \
    sed -i 's/^mirrorlist=http/#mirrorlist=http/g' /etc/yum.repos.d/*.repo
   
# use node 10 as it's guaranteed to run on CentOS6
RUN yum-config-manager --enable rhel-server-rhscl-7-rpms && \
    yum install -y devtoolset-10 libffi-devel patch wget zlib-devel && \
    wget -q https://nodejs.org/dist/v10.23.0/node-v10.23.0-linux-x64.tar.gz && \
    tar -xf node-v10.23.0-linux-x64.tar.gz && \ 
    rm node-v10.23.0-linux-x64.tar.gz && \
    ln -s /node-v10.23.0-linux-x64/bin/node /bin/node && \ 
    ln -s /node-v10.23.0-linux-x64/bin/npm /bin/npm 

# Build and install Python 3.9 as a prerequisite for building Node.js 24
RUN wget https://www.python.org/ftp/python/3.9.21/Python-3.9.21.tgz && \
    tar -xvf Python-3.9.21.tgz && \
    cd Python-3.9.21 && \
    ./configure --prefix=/usr/local && \
    make

RUN make altinstall

#RUN ln -fs /usr/bin/python3 /usr/bin/python

# before building using this container you need to enable the right slc toolchain ie
# scl enable devtoolset-8 '<your-build-command-here>'
# or 'source /opt/rh/devtoolset-8/enable'